name: Package
on:
  push:
    branches:
      - master
    paths:
      - 'MediatREndPoints.nuspec'
jobs:
  publish:
    name: Publish to NuGet.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}

      - name: Create the package
        run: nuget pack MediatREndPoints.nuspec -NoDefaultExcludes
        
      - name: Publish the package
        run: nuget push *.nupkg -source 'https://api.nuget.org/v3/index.json' -SkipDuplicate -configuration Release
